version: 1.0.{build}
platform: x64
branches:
  only:
  - dev
build:
  verbosity: minimal
notifications:
- provider: Email
  to:
  - mail@pygimli.org
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

environment:
  BOOST_ROOT: c:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: c:\Libraries\boost_1_59_0\stage\lib

build_script:
    - set PATH=C:\msys64\usr\bin;%PATH%
    - C:\msys64\usr\bin\bash -lc "curl -sL http://install.pygimli.org | bash"
