# Configuration file for continous integration using travis.
# See build results on http://travis-ci.org/gimli-org/gimli
# Before commiting changes to this file, check consistency on http://lint.travis-ci.org/

# Most explicit routing to GCE Precise
sudo: true
dist: trusty

os: linux

language: python

python:
  - "3.4"

#branches:
  #only:
    #- dev

#osx_image: xcode7.2b2

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest

    packages:
    # ESSENTIALS
    - cmake
    - build-essential
    - coreutils
    - g++-5
    - gcc-5
    
    # DOC
    - doxygen
    - doxygen-latex
    - dvipng

    # BLAS, LAPACK, BOOST
    - libblas-dev
    - liblapack-dev
    - libsuitesparse-dev
    - libedit-dev
    - libboost-system1.55-dev 
    - libboost-thread1.55-dev
    - libboost-python1.55-dev

    # PYTHON3
    - python3-dev
    - python3-pytest
    - python3-numpy
    - python3-matplotlib
    - python3-sphinx

cache:
  apt: True
  pip: True
  directories:
    - $HOME/thirdParty
    - $HOME/build

env:
  global:
    - LLVM_VERSION=3.7.0
    - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz

before_install:
  # Install LLVM manually due to broken APT sources
  - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
  - mkdir $HOME/clang+llvm
  - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang+llvm --strip-components 1
  - export PATH=$HOME/clang+llvm/bin:$PATH
  - export CXX="g++-5" CC="gcc-5"

install:
  # Show Infos
  - uname -a
  - gcc --version
  - python --version
  - cmake --version
  - python -c "import numpy; print(numpy.__version__)"

  # Documentation requirements
  - pip --version
  - pip install -r doc/requirements.txt

  # Main build
  - mkdir trunk
  - shopt -s extglob
  - mv !(trunk|build|thirdParty) trunk # necessary because of lib and thirdParty backcopying
  - mkdir -p build
  - cd build
  - cmake ../trunk
  - make -j 4 gimli
  - make pygimli J=4

script:
  # Test gimli
  - make check
  - ./bin/gimliUnitTest
  
  # Test pygimli
  - export PATH=`pwd`/bin:$PATH
  - export PYTHONPATH=$PYTHONPATH:`pwd`/../trunk/python
  - python -c "import pygimli; pygimli.test(show=False)"
  
  # Test doc build
  - make html

#notifications:
#email:
    #recipients:
    #- mail@pygimli.org
