# Configuration file for continous integration using travis.
# See build results on http://travis-ci.org/gimli-org/gimli
# Before commiting changes to this file, check consistency on http://lint.travis-ci.org/

# Most explicit routing to GCE Precise
sudo: false
dist: precise

os: linux

language: c++

#python:
  #- "3.4"

#branches:
  #only:
    #- dev

#osx_image: xcode7.2b2

addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.7
    - kalakris-cmake
    - ubuntu-toolchain-r-test
    - boost-latest

    packages:
    # ESSENTIALS
    - cmake
    - build-essential
    - coreutils
    - clang-3.7
    - libclang-3.7-dev
    - llvm-3.7
    - libllvm-3.7-ocaml-dev
    - g++-5
    - gcc-5

    # BLAS, LAPACK, BOOST
    - libblas-dev
    - liblapack-dev
    - libsuitesparse-dev
    - libedit-dev
    - libboost1.55-all-dev

    # PYTHON3
    - python3-dev
    - python-pytest
    - python3-numpy
    - python-matplotlib

cache:
  - apt

install:
  - export CXX="g++-5" CC="gcc-5"
  - curl -sL http://install.pygimli.org | bash -s py=3 j=4

script:
  - python -c "import pygimli; pygimli.test(show=False)"

#notifications:
#email:
    #recipients:
    #- mail@pygimli.org
