# Configuration file for continous integration using travis.
# See build results on http://travis-ci.org/gimli-org/gimli
# Before commiting changes to this file, check consistency on http://lint.travis-ci.org/

# Most explicit routing to GCE Precise
sudo: false

os:
    - linux
      #- osx

language: cpp

#branches:
  #only:
    #- dev

#osx_image: xcode7.2b2

addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.7
    - kalakris-cmake
    - ubuntu-toolchain-r-test

    packages:
    # Essentials
    - cmake
    - build-essential
    - coreutils
    - clang-3.7
    - libclang-3.7-dev
    - llvm-3.7
    - libllvm-3.7-ocaml-dev

    # Blas, Lapack, boost
    - libblas-dev
    - liblapack-dev
    - libsuitesparse-dev
    - libedit-dev
    - libboost1.55-all-dev
    #- libboost-all-dev

    # Python3
    - python3-dev
    - python3-numpy
    #- python3-matplotlib
    #- python3-pytest

#before_install:
    ## hack automatic OS detection
    #- echo 'NAME="Ubuntu"' | sudo tee /etc/os-release
    #- echo 'VERSION="14.04.2 LTS, Trusty Tahr"' | sudo tee -a /etc/os-release
    #- echo 'ID=ubuntu' | sudo tee -a /etc/os-release
    #- echo 'ID_LIKE=debian' | sudo tee -a /etc/os-release
    #- echo 'PRETTY_NAME="Ubuntu 14.04.2 LTS"' | sudo tee -a /etc/os-release
    #- echo 'VERSION_ID="14.04"' | sudo tee -a /etc/os-release
    #- echo 'HOME_URL="http://www.ubuntu.com/"' | sudo tee -a /etc/os-release

install:
    - curl -sL http://install.pygimli.org | bash -s py=3 j=4

#notifications:
#email:
    #recipients:
    #- mail@pygimli.org
