# Configuration file for continous integration using travis.
# See build results on http://travis-ci.org/gimli-org/gimli
# Before commiting changes to this file, check consistency on http://lint.travis-ci.org/

language: python

os: linux

compiler: clang

python:
    - "2.7"
    - "3.4"

#sudo: false # activates new container-based infrastructure (faster)

cache:
    directories:
    - thirdParty
    
before_install:
    # APT-GET (should be reduced or better removed completely)
    - sudo apt-get update -qq
    - sudo apt-get install -qq libblas-dev liblapack-dev
    - sudo apt-get install -qq libsuitesparse-dev

    # CONDA
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
        else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - DEPS="cmake boost numpy matplotlib sphinx"
    - conda create -q -n gimli python=$TRAVIS_PYTHON_VERSION $DEPS
    - source activate gimli
    - pip install -r doc/requirements.txt
    - conda install -c http://conda.anaconda.org/numba llvmdev

install:
    # Show Infos
    - uname -a
    - clang --version
    - python --version
    - cmake --version
    - python -c "import numpy; print(numpy.__version__)"

    # Main build
    - mkdir trunk
    - shopt -s extglob
    - mv !(trunk) trunk # necessary because of lib and thirdParty backcopying
    - mkdir build
    - cd build
    - cmake ../trunk -DPYTHON_LIBRARY=/home/travis/miniconda/envs/gimli/lib/libpython3.so
    - make -j 4 gimli
    - make pygimli J=4

script:
    # Test gimli
    - make check
    - ./bin/gimliUnitTest

    # Make sure that interactive matplotlib backends work
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

    # Test pygimli
    - export PYTHONPATH=$PYTHONPATH:`pwd`/../trunk/python
    - python -c "import pygimli; pygimli.test(onlydoctests=False, htmlreport='build_tests.html')"
    - chmod +x ../trunk/python/apps/*
    - make doc
