# Configuration file for continous integration using travis.
# See build results on http://travis-ci.org/gimli-org/gimli
# Before commiting changes to this file, check consistency on http://lint.travis-ci.org/

# Most explicit routing to GCE Precise
sudo: required
dist: trusty

os: linux

language: c++

#python:
  #- "3.4"

#branches:
  #only:
    #- dev

#osx_image: xcode7.2b2

addons:
  apt:
    sources:
    - kalakris-cmake
    - ubuntu-toolchain-r-test
    - boost-latest

    packages:
    # ESSENTIALS
    - cmake
    - build-essential
    - coreutils
    - g++-5
    - gcc-5

    # BLAS, LAPACK, BOOST
    - libblas-dev
    - liblapack-dev
    - libsuitesparse-dev
    - libedit-dev
    - libboost1.55-all-dev

    # PYTHON3
    - python3-dev
    - python-pytest
    - python3-numpy
    - python-matplotlib

cache:
  - apt

env:
  global:
    - LLVM_VERSION=3.7.0
    - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz

before_install:
  # Install LLVM manually due to broken APT sources
  - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
  - mkdir $HOME/clang+llvm
  - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang+llvm --strip-components 1
  - export PATH=$HOME/clang+llvm/bin:$PATH
  - export CXX="g++-5" CC="gcc-5"

install:

  # Install doc requirements
  - cd doc
  - sudo pip install -q -U -r requirements.txt
  - cd ..

  # Show Infos
  - uname -a
  - gcc --version
  - python --version
  - cmake --version
  - python -c "import numpy; print(numpy.__version__)"

  # Main build
  - mkdir trunk
  - shopt -s extglob
  - mv !(trunk) trunk # necessary because of lib and thirdParty backcopying
  - mkdir build
  - cd build
  - cmake ../trunk
  - make -j 4 gimli
  - make pygimli J=3

script:
  - python -c "import pygimli; pygimli.test(show=False)"

#notifications:
#email:
    #recipients:
    #- mail@pygimli.org
