# Configuration file for continous integration using travis.
# See build results on http://travis-ci.org/gimli-org/gimli
# Before commiting changes to this file, check consistency on http://lint.travis-ci.org/

language: cpp

sudo: required

compiler: clang

os:
    - linux
    - osx

env:
    global:
    - CXX="clang++-3.6"
    - CC="clang-3.6"
    matrix:
    - PYVERSION=2.7
    - PYVERSION=3.4

# Don't try py2 build on MacOSX
#matrix:
  #exclude:
    #- os: osx
      #env: PYVERSION=2.7

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - clang-3.6
    - libclang-3.6-dev
    - llvm-3.6
    - libllvm-3.6-ocaml-dev
    - libblas-dev
    - liblapack-dev
    - libsuitesparse-dev
    - libedit-dev
    - libboost-all-dev

cache:
    directories:
    - thirdParty

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        OSNAME="MacOSX";
        brew update;
        brew unlink boost cmake;
        #brew install llvm36 --with-clang;
        brew install cmake boost boost-python libconfig;
      elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        OSNAME="Linux";
      fi
    - if [ "PYVERSION" == "2.7" ]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-$OSNAME-x86_64.sh -O miniconda.sh;
        else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-$OSNAME-x86_64.sh -O miniconda.sh;
        fi

    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - DEPS="cmake numpy matplotlib sphinx"
    - conda create -q -n gimli python=$PYVERSION $DEPS
    - source activate gimli
    - conda install -c http://conda.anaconda.org/numba llvmdev
    - pip install -r doc/requirements.txt # documentation requirements

install:
    # Show Infos
    - uname -a
    - python --version
    - cmake --version
    - python -c "import numpy; print(numpy.__version__)"

    # Main build
    - mkdir trunk
    - shopt -s extglob
    - mv !(trunk) trunk # necessary because of lib and thirdParty backcopying
    - mkdir build
    - cd build
    - cmake ../trunk
    - make -j 4 gimli
    - make pygimli J=4

script:
    # Test gimli
    - make check
    - ./bin/gimliUnitTest

    # Make sure that interactive matplotlib backends work
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

    # Test pygimli
    - export PYTHONPATH=$PYTHONPATH:`pwd`/../trunk/python
    - python -c "import pygimli; pygimli.test(onlydoctests=False, htmlreport='build_tests.html')"
